services:
  postgres:
    image: postgres:17.6-alpine
    container_name: dataset_db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - datasets_postgres_data:/var/lib/postgresql/data

volumes:
  datasets_postgres_data:
